import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { generateCss } from '../src/generator/css';
import {
  generateReactComponent,
  getComponentName,
} from '../src/generator/react';
import { generateTailwindCss } from '../src/generator/tailwind';
import { getRegistryItem, type RegistryItem } from '../src/registry';

export type GlypheConfig = {
  output: {
    components: string;
    css: string;
    tailwind: string;
  };
};

export type InstallOutput = 'css' | 'react' | 'tailwind';

export type InstallOptions = {
  slug: string;
  cwd: string;
  outputs: InstallOutput[];
  dryRun?: boolean;
  force?: boolean;
  componentName?: string;
  config?: GlypheConfig;
};

export type PlannedFile = {
  path: string;
  content: string;
  action: 'create' | 'update' | 'conflict';
  reason: string;
};

export type InstallPlan = {
  item: RegistryItem;
  files: PlannedFile[];
};

const defaultConfig: GlypheConfig = {
  output: {
    components: 'src/components/glyphe',
    css: 'src/styles/glyphe.css',
    tailwind: 'src/styles/glyphe-tailwind.css',
  },
};

const marker = 'Generated by Glyphe. You own this file.';

export async function createLocalInstallPlan(
  options: InstallOptions,
): Promise<InstallPlan> {
  const item = getRegistryItem(options.slug);

  if (!item) {
    throw new Error(`Registry item not found: ${options.slug}`);
  }

  const config = options.config ?? defaultConfig;
  const files = await Promise.all(
    options.outputs.map((output) =>
      planOutputFile({ ...options, config, item, output }),
    ),
  );

  return {
    item,
    files,
  };
}

export async function installLocalRegistryItem(options: InstallOptions) {
  const plan = await createLocalInstallPlan(options);
  const conflicts = plan.files.filter((file) => file.action === 'conflict');

  if (conflicts.length > 0) {
    throw new Error(
      `Refusing to overwrite unmanaged files: ${conflicts
        .map((file) => file.path)
        .join(', ')}`,
    );
  }

  if (options.dryRun) {
    return plan;
  }

  await Promise.all(
    plan.files.map(async (file) => {
      await mkdir(dirname(file.path), { recursive: true });
      await writeFile(file.path, file.content);
    }),
  );

  return plan;
}

async function planOutputFile({
  item,
  output,
  cwd,
  force,
  componentName,
  config,
}: InstallOptions & {
  item: RegistryItem;
  output: InstallOutput;
  config: GlypheConfig;
}) {
  const generated = generateOutput({ item, output, componentName });
  const path = getOutputPath({ item, output, cwd, componentName, config });
  const existing = await readExistingFile(path);

  if (!existing) {
    return {
      path,
      content: generated,
      action: 'create',
      reason: 'file does not exist',
    } satisfies PlannedFile;
  }

  if (output === 'react' && !force && !existing.includes(marker)) {
    return {
      path,
      content: existing,
      action: 'conflict',
      reason: 'existing component is not marked as Glyphe-managed',
    } satisfies PlannedFile;
  }

  return {
    path,
    content: mergeGeneratedBlock({
      existing,
      generated,
      force,
      slug: item.slug,
      output,
    }),
    action: 'update',
    reason: 'file exists',
  } satisfies PlannedFile;
}

function generateOutput({
  item,
  output,
  componentName,
}: {
  item: RegistryItem;
  output: InstallOutput;
  componentName?: string;
}) {
  if (output === 'react') {
    return withManagedMarker(
      item.slug,
      output,
      generateReactComponent(item, { componentName }),
    );
  }

  if (output === 'tailwind') {
    return withManagedMarker(item.slug, output, generateTailwindCss(item));
  }

  return withManagedMarker(item.slug, output, generateCss(item));
}

function getOutputPath({
  item,
  output,
  cwd,
  componentName,
  config,
}: {
  item: RegistryItem;
  output: InstallOutput;
  cwd: string;
  componentName?: string;
  config: GlypheConfig;
}) {
  if (output === 'react') {
    const name = componentName ?? getComponentName(item);

    return join(cwd, config.output.components, `${name}.tsx`);
  }

  if (output === 'tailwind') {
    return join(cwd, config.output.tailwind);
  }

  return join(cwd, config.output.css);
}

function withManagedMarker(
  slug: string,
  output: InstallOutput,
  content: string,
) {
  return `/* ${marker} */\n/* glyphe:start ${slug} ${output} */\n${content}\n/* glyphe:end ${slug} ${output} */\n`;
}

function mergeGeneratedBlock({
  existing,
  generated,
  force,
  slug,
  output,
}: {
  existing: string;
  generated: string;
  force?: boolean;
  slug: string;
  output: InstallOutput;
}) {
  const blockPattern = new RegExp(
    `/\\* ${escapeRegExp(marker)} \\*/\\n/\\* glyphe:start ${escapeRegExp(
      slug,
    )} ${output} \\*/[\\s\\S]*?/\\* glyphe:end ${escapeRegExp(slug)} ${output} \\*/\\n?`,
  );

  if (blockPattern.test(existing)) {
    return existing.replace(blockPattern, generated);
  }

  if (output === 'react' && force) {
    return generated;
  }

  return `${existing.trimEnd()}\n\n${generated}`;
}

async function readExistingFile(path: string) {
  try {
    return await readFile(path, 'utf8');
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') {
      return null;
    }

    throw error;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
